# Site settings
name: Vivek Teegalapally
title: Vivek Teegalapally | Senior DevOps & SRE Engineer
description: Senior DevOps & SRE Engineer building resilient infrastructure for blockchain networks and the cloud
url: https://vivekteega.com/
baseurl: ''
email: vivek.teega@gmail.com
cover: https://vivekteega.com/img/og.png?v=2
logo: https://vivekteega.com/img/emojis/technologist.png
resume: https://vivekteega.com/resume.pdf
social:
  - title: email
    url: mailto:vivek.teega@gmail.com
  - title: twitter
    url: https://twitter.com/vivekteega
  - title: github
    url: https://github.com/vivekteega
  - title: linkedin
    url: https://www.linkedin.com/in/vivekteega

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
