# Site settings
name: Vivek Teega
title: Vivek Teega | Blockchain Developer
description: Blockchain Developer writing apps on FLO blockchain using JavaScript & Python
url: https://vivekteega.github.io/
baseurl: ''
email: vivek.teega@gmail.com
cover: https://vivekteega.github.io/img/og.png
logo: https://vivekteega.github.io/img/emojis/technologist.png
resume: https://vivekteega.github.io/resume.pdf
social:
  - title: email
    url: mailto:vivek.teega@gmail.com
  - title: twitter
    url: https://twitter.com/vivekteega
  - title: instagram
    url: https://instagram.com/vivekteega
  - title: codepen
    url: http://codepen.io/vivekteega
  - title: github
    url: https://github.com/vivekteega
  - title: linkedin
    url: https://www.linkedin.com/in/vivekteega

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
